on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - run: ./@v1/publish.sh
