on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "maxnorth.github-actions-monolith"
          git config --global user.email "maxnorth.github-actions-monolith@github.com"
      - run: ./@v1/publish.sh
